# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6e821f294603f9a78ee8620c440ad4cf5031b53f1cb11a0351eec3504d4bf1cadba7572efe8e462b849c86c3cfa204033d0bcc195cc93c363fffc4443ea4a39

test:
  secret_key_base: 38d20ef03abe60758f9085dcce89f06c578a398a89c56ac5501c26dcaea6f75dc274d41cc71d4dae0799f5f43c506fc3c69074dd2fff97c05bcf021938ce0702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
